services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: TA_backend
    env_file:
      - ./setting/.env
    environment:
      - DATABASE_URL
    volumes:
      - .:/app
    networks:
      - TravelArchiveNetwork
    expose:
      # 호스트 노출(ports)이 아닌, 동일 도커 네트워크 내 Nginx에게만 8000번 포트를 엽니다.
      - "8000"
    restart: always

networks:
  TravelArchiveNetwork:
    external: true