services:
  db:
    # 블로그에서 검증된 라즈베리파이 4 (ARM64) 완벽 호환 이미지
    image: kartoza/postgis:18-3.6
    container_name: TA_db
    env_file:
      - ./setting/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      # OMV NAS 절대 경로
      - ./db/data:/var/lib/postgresql/18/main
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - TravelArchiveNetwork
    restart: always

networks:
  TravelArchiveNetwork:
    external: true